//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dinamicos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dinamicos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Dinamicos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebidas.
        /// </summary>
        internal static string Bebidas {
            get {
                return ResourceManager.GetString("Bebidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Café express.
        /// </summary>
        internal static string Cafe_express {
            get {
                return ResourceManager.GetString("Cafe_express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe express muy rico.
        /// </summary>
        internal static string Cafe_express_descripcion {
            get {
                return ResourceManager.GetString("Cafe_express_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerveza.
        /// </summary>
        internal static string Cerveza {
            get {
                return ResourceManager.GetString("Cerveza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerveza muy rica.
        /// </summary>
        internal static string Cerveza_descripcion {
            get {
                return ResourceManager.GetString("Cerveza_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef en Jefe.
        /// </summary>
        internal static string Chef_1_cargo {
            get {
                return ResourceManager.GetString("Chef_1_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EspanolLorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem..
        /// </summary>
        internal static string Chef_1_descripcion {
            get {
                return ResourceManager.GetString("Chef_1_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef ayudante.
        /// </summary>
        internal static string Chef_2_cargo {
            get {
                return ResourceManager.GetString("Chef_2_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EspanolLorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis,.
        /// </summary>
        internal static string Chef_2_descripcion {
            get {
                return ResourceManager.GetString("Chef_2_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef abuela.
        /// </summary>
        internal static string Chef_3_cargo {
            get {
                return ResourceManager.GetString("Chef_3_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EspanolLorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesq.
        /// </summary>
        internal static string Chef_3_descripcion {
            get {
                return ResourceManager.GetString("Chef_3_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensalada fría.
        /// </summary>
        internal static string Ensalada_fria {
            get {
                return ResourceManager.GetString("Ensalada_fria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensalada fría muy rica.
        /// </summary>
        internal static string Ensalada_fria_descripcion {
            get {
                return ResourceManager.GetString("Ensalada_fria_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrantes.
        /// </summary>
        internal static string Entrantes {
            get {
                return ResourceManager.GetString("Entrantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastas.
        /// </summary>
        internal static string Pastas {
            get {
                return ResourceManager.GetString("Pastas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postres.
        /// </summary>
        internal static string Postres {
            get {
                return ResourceManager.GetString("Postres", resourceCulture);
            }
        }
    }
}
