//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaladarHostal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaladarHostal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaladarHostal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string Abril {
            get {
                return ResourceManager.GetString("Abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompañantes.
        /// </summary>
        internal static string Acompannantes {
            get {
                return ResourceManager.GetString("Acompannantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string Anno {
            get {
                return ResourceManager.GetString("Anno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        internal static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baño interior - agua fria/caliente las 24 horas.
        /// </summary>
        internal static string Banno_interior {
            get {
                return ResourceManager.GetString("Banno_interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        internal static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si desea cancelar o modificar los datos de su reservación acceda a la siguiente dirección web.
        /// </summary>
        internal static string Cancelar_reservacion {
            get {
                return ResourceManager.GetString("Cancelar_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentamos informarle que ha sido cancelada su reservación con los datos.
        /// </summary>
        internal static string Cancelar_reservacion_cliente {
            get {
                return ResourceManager.GetString("Cancelar_reservacion_cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        internal static string Cerrado {
            get {
                return ResourceManager.GetString("Cerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string Cerrar {
            get {
                return ResourceManager.GetString("Cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Chefs.
        /// </summary>
        internal static string Chefs {
            get {
                return ResourceManager.GetString("Chefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic o arrastre una imagen.
        /// </summary>
        internal static string Click_arrastrar {
            get {
                return ResourceManager.GetString("Click_arrastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        internal static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios recientes.
        /// </summary>
        internal static string Comentarios_recientes {
            get {
                return ResourceManager.GetString("Comentarios_recientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentario....
        /// </summary>
        internal static string Comentario_comentario {
            get {
                return ResourceManager.GetString("Comentario_comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentar ahora....
        /// </summary>
        internal static string Comentar_ahora {
            get {
                return ResourceManager.GetString("Comentar_ahora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión a Internet.
        /// </summary>
        internal static string Conexion_internet {
            get {
                return ResourceManager.GetString("Conexion_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conozca el Equipo.
        /// </summary>
        internal static string Conozca_equipo {
            get {
                return ResourceManager.GetString("Conozca_equipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contáctenos.
        /// </summary>
        internal static string Contactenos {
            get {
                return ResourceManager.GetString("Contactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Contrasenna {
            get {
                return ResourceManager.GetString("Contrasenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los derechos reservados.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortesía de la Casa.
        /// </summary>
        internal static string Cortesia_casa {
            get {
                return ResourceManager.GetString("Cortesia_casa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sus credenciales son.
        /// </summary>
        internal static string Credenciales {
            get {
                return ResourceManager.GetString("Credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales no son válidas..
        /// </summary>
        internal static string Credenciales_invalidas {
            get {
                return ResourceManager.GetString("Credenciales_invalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de contacto.
        /// </summary>
        internal static string Datos_contacto {
            get {
                return ResourceManager.GetString("Datos_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de reservación.
        /// </summary>
        internal static string Datos_reservacion {
            get {
                return ResourceManager.GetString("Datos_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEJA TU COMENTARIO.
        /// </summary>
        internal static string Deja_comentario {
            get {
                return ResourceManager.GetString("Deja_comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su reservación ha sido denegada, no podemos comunicarnos con su correo..
        /// </summary>
        internal static string Denegar_correo {
            get {
                return ResourceManager.GetString("Denegar_correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ofrecemos el servicio de conexión a internet mediante la red WIFI desde nuestra casa para asegurar su comodidad..
        /// </summary>
        internal static string Descripcion_conexion_internet {
            get {
                return ResourceManager.GetString("Descripcion_conexion_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mostraremos una colección de fotografías de nuestra casa, las cuales le servirán de recorrido para que conozca nuestro negocio. Tendrá la oportunidad de ver las habitaciones, el garage y mucho máas. No pierda tiempo, visítenos!!!.
        /// </summary>
        internal static string Descripcion_galeria_hostal {
            get {
                return ResourceManager.GetString("Descripcion_galeria_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le invitamos a compartir con nosotros sus maravillosas vivencias en la hermosa Trinidad de Cuba, ofreciéndole la posibilidad de subir imágenes a nuestra galería donde podrá disfrutar de una selección de las mejores fotografías tomadas en nuestra Paladar. ¡No pierda tiempo, le aseguramos una Atención Exquisita!.
        /// </summary>
        internal static string Descripcion_galeria_imagenes {
            get {
                return ResourceManager.GetString("Descripcion_galeria_imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitorios placenteros y seguros para su confort..
        /// </summary>
        internal static string Descripcion_habitaciones {
            get {
                return ResourceManager.GetString("Descripcion_habitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disfrute de la variedad y exquisitez de nuestra comida.
        /// </summary>
        internal static string Descripcion_publicidad1 {
            get {
                return ResourceManager.GetString("Descripcion_publicidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garantizamos comodidad y deleite al máximo..
        /// </summary>
        internal static string Descripcion_publicidad1_hostal {
            get {
                return ResourceManager.GetString("Descripcion_publicidad1_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brindamos un servicio rápido y de gran calidad.
        /// </summary>
        internal static string Descripcion_publicidad2 {
            get {
                return ResourceManager.GetString("Descripcion_publicidad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridamos un servicio de calidad donde usted es nuestra prioridad..
        /// </summary>
        internal static string Descripcion_publicidad2_hostal {
            get {
                return ResourceManager.GetString("Descripcion_publicidad2_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelente opción para disfutar de una comida en familia.
        /// </summary>
        internal static string Descripcion_publicidad3 {
            get {
                return ResourceManager.GetString("Descripcion_publicidad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajamos para brindarle una experiencia placentera y estimulante..
        /// </summary>
        internal static string Descripcion_publicidad3_hostal {
            get {
                return ResourceManager.GetString("Descripcion_publicidad3_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le brindamos la posibilidad de reservar en nuestra paladar con los días de antelación y en la hora que usted estime conveniente. Solo tiene que enviar una solicitud con su nombre completo, la cantidad de personas y la fecha en la que desea reservar..
        /// </summary>
        internal static string Descripcion_Reservar {
            get {
                return ResourceManager.GetString("Descripcion_Reservar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontrará un lugar con las condiciones necesarias para estacionar su auto de manera segura y confiable en nuestro garaje..
        /// </summary>
        internal static string Descripcion_servicio_garage {
            get {
                return ResourceManager.GetString("Descripcion_servicio_garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofrecemos un servicio de lavandería rápido y eficiente para usted y su familia..
        /// </summary>
        internal static string Descripcion_servicio_lavanderia {
            get {
                return ResourceManager.GetString("Descripcion_servicio_lavanderia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puede disfrutar de exquisitos y diversos platos en nuestro negocio de Paladar, estaríamos encantados de servirle..
        /// </summary>
        internal static string Descripcion_servicio_paladar {
            get {
                return ResourceManager.GetString("Descripcion_servicio_paladar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estaremos encantados de recibirlo en nuestra casa..
        /// </summary>
        internal static string Descripcion_solicitud_reservacion {
            get {
                return ResourceManager.GetString("Descripcion_solicitud_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea eliminar la reservación.
        /// </summary>
        internal static string Desea_eliminar_reservacion {
            get {
                return ResourceManager.GetString("Desea_eliminar_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        internal static string Diciembre {
            get {
                return ResourceManager.GetString("Diciembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle Chanzoneta #271 entre San Procopio y Luz, Trinidad..
        /// </summary>
        internal static string Direccion_negocio {
            get {
                return ResourceManager.GetString("Direccion_negocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        internal static string Domingo {
            get {
                return ResourceManager.GetString("Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar imagen.
        /// </summary>
        internal static string Eliminar_imagen {
            get {
                return ResourceManager.GetString("Eliminar_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar reservación.
        /// </summary>
        internal static string Eliminar_reservacion {
            get {
                return ResourceManager.GetString("Eliminar_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        internal static string Enero {
            get {
                return ResourceManager.GetString("Enero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string Entrar {
            get {
                return ResourceManager.GetString("Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar mensaje.
        /// </summary>
        internal static string Enviar_mensaje {
            get {
                return ResourceManager.GetString("Enviar_mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo realizar la reservación, inténtelo nuevamente..
        /// </summary>
        internal static string Error_crear_reservacion {
            get {
                return ResourceManager.GetString("Error_crear_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al intentar eliminar la imagen..
        /// </summary>
        internal static string Error_eliminar_image {
            get {
                return ResourceManager.GetString("Error_eliminar_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar la reservación, inténtelo nuevamente..
        /// </summary>
        internal static string Error_eliminar_reservacion {
            get {
                return ResourceManager.GetString("Error_eliminar_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico entrado no es válido..
        /// </summary>
        internal static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha que seleccionó ha expirado..
        /// </summary>
        internal static string Error_fecha_reservacion {
            get {
                return ResourceManager.GetString("Error_fecha_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El horario de reservación es de 11:00 AM - 09:00 PM..
        /// </summary>
        internal static string Error_horario_reservacion {
            get {
                return ResourceManager.GetString("Error_horario_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La imagen excede los 10MB.
        /// </summary>
        internal static string Error_imagen_tamanno {
            get {
                return ResourceManager.GetString("Error_imagen_tamanno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos! No podemos efrecerle la ubicación en este momento..
        /// </summary>
        internal static string Error_ubicacion {
            get {
                return ResourceManager.GetString("Error_ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una reservación para la fecha y habitaciones seleccionadas..
        /// </summary>
        internal static string Existe_reservacion_hostal {
            get {
                return ResourceManager.GetString("Existe_reservacion_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        internal static string Febrero {
            get {
                return ResourceManager.GetString("Febrero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha entrada.
        /// </summary>
        internal static string Fecha_entrada {
            get {
                return ResourceManager.GetString("Fecha_entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de entrada no puede ser mayor que la fecha de salida..
        /// </summary>
        internal static string Fecha_ent_may_sal {
            get {
                return ResourceManager.GetString("Fecha_ent_may_sal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha salida.
        /// </summary>
        internal static string Fecha_salida {
            get {
                return ResourceManager.GetString("Fecha_salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajamos para usted, nuestro estimado cliente, con el fin de brindarle un servicio de calidad y confort. Ofrecemos además el servicio de.
        /// </summary>
        internal static string Footer_primero_hostal {
            get {
                return ResourceManager.GetString("Footer_primero_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donde le aseguramos un espacio para degustar deliciosas bebidas y saborear una diversidad de ricas comidas criollas a su disposición las 24 horas. No pierda tiempo, visítenos!!!.
        /// </summary>
        internal static string Footer_segundo_hostal {
            get {
                return ResourceManager.GetString("Footer_segundo_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francés.
        /// </summary>
        internal static string Frances {
            get {
                return ResourceManager.GetString("Frances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocinar todo con respeto dará lugar a experiencias de degustación increíbles.
        /// </summary>
        internal static string Frase {
            get {
                return ResourceManager.GetString("Frase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería.
        /// </summary>
        internal static string Galeria {
            get {
                return ResourceManager.GetString("Galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galería de Imágenes.
        /// </summary>
        internal static string Galeria_imagenes {
            get {
                return ResourceManager.GetString("Galeria_imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garaje.
        /// </summary>
        internal static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por preferirnos, nuestro equipo le desea un excelente día..
        /// </summary>
        internal static string Gracias_preferencia {
            get {
                return ResourceManager.GetString("Gracias_preferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        internal static string Habitaciones {
            get {
                return ResourceManager.GetString("Habitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera Habitación.
        /// </summary>
        internal static string Habitacion_1 {
            get {
                return ResourceManager.GetString("Habitacion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segunda Habitación.
        /// </summary>
        internal static string Habitacion_2 {
            get {
                return ResourceManager.GetString("Habitacion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitación doble.
        /// </summary>
        internal static string Habitacion_doble {
            get {
                return ResourceManager.GetString("Habitacion_doble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitación sencilla.
        /// </summary>
        internal static string Habitacion_sencilla {
            get {
                return ResourceManager.GetString("Habitacion_sencilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hasta el.
        /// </summary>
        internal static string Hasta_el {
            get {
                return ResourceManager.GetString("Hasta_el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario.
        /// </summary>
        internal static string Horario {
            get {
                return ResourceManager.GetString("Horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario y Datos de interés.
        /// </summary>
        internal static string Horario_Datos {
            get {
                return ResourceManager.GetString("Horario_Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostal.
        /// </summary>
        internal static string Hostal {
            get {
                return ResourceManager.GetString("Hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen.
        /// </summary>
        internal static string Imagen {
            get {
                return ResourceManager.GetString("Imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes.
        /// </summary>
        internal static string Imagenes {
            get {
                return ResourceManager.GetString("Imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string Informacion {
            get {
                return ResourceManager.GetString("Informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información! Su reservación se realizó correctamente..
        /// </summary>
        internal static string Info_Reservacion {
            get {
                return ResourceManager.GetString("Info_Reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglés.
        /// </summary>
        internal static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        internal static string Jueves {
            get {
                return ResourceManager.GetString("Jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        internal static string Julio {
            get {
                return ResourceManager.GetString("Julio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        internal static string Junio {
            get {
                return ResourceManager.GetString("Junio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitud.
        /// </summary>
        internal static string Latitud {
            get {
                return ResourceManager.GetString("Latitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavandería.
        /// </summary>
        internal static string Lavanderia {
            get {
                return ResourceManager.GetString("Lavanderia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud.
        /// </summary>
        internal static string Longitud {
            get {
                return ResourceManager.GetString("Longitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        internal static string Lunes {
            get {
                return ResourceManager.GetString("Lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        internal static string Martes {
            get {
                return ResourceManager.GetString("Martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        internal static string Marzo {
            get {
                return ResourceManager.GetString("Marzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Más Comentarios....
        /// </summary>
        internal static string Mas_comentarios {
            get {
                return ResourceManager.GetString("Mas_comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        internal static string Mayo {
            get {
                return ResourceManager.GetString("Mayo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje adicional.
        /// </summary>
        internal static string Mensaje_adicional {
            get {
                return ResourceManager.GetString("Mensaje_adicional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El mensaje se envió correctamente..
        /// </summary>
        internal static string Mensaje_enviado {
            get {
                return ResourceManager.GetString("Mensaje_enviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al enviar el mensaje, inténtelo nuevamente..
        /// </summary>
        internal static string Mensaje_error {
            get {
                return ResourceManager.GetString("Mensaje_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes.
        /// </summary>
        internal static string Mes {
            get {
                return ResourceManager.GetString("Mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miércoles.
        /// </summary>
        internal static string Miercoles {
            get {
                return ResourceManager.GetString("Miercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minibar.
        /// </summary>
        internal static string Minibar {
            get {
                return ResourceManager.GetString("Minibar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar reservación.
        /// </summary>
        internal static string Modificar_reservacion {
            get {
                return ResourceManager.GetString("Modificar_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestro Negocio.
        /// </summary>
        internal static string Negocio {
            get {
                return ResourceManager.GetString("Negocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Hostal Emelina Santander es una casa moderna, se encuentra ubicado en la bella ciudad de Trinidad. El alojamiento cuenta con 2 habitaciones climatizadas, cada una con baño interior con agua fría y caliente las 24 horas, además de garaje privado con espacio para 2 automóviles. Se ofrece servicio a su disposición de gastronomía: exquisitos desayunos, almuerzos y comidas tradicionales cubanas. Posee un amplio patio interior con 2 sillones para disfrutar de una fantástica puesta de sol, incluye además un por [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Negocio_Hostal {
            get {
                return ResourceManager.GetString("Negocio_Hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noche.
        /// </summary>
        internal static string Noche {
            get {
                return ResourceManager.GetString("Noche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellidos.
        /// </summary>
        internal static string Nombre_apellidos {
            get {
                return ResourceManager.GetString("Nombre_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Apellidos.....
        /// </summary>
        internal static string Nombre_apellidos_comentario {
            get {
                return ResourceManager.GetString("Nombre_apellidos_comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        internal static string Noviembre {
            get {
                return ResourceManager.GetString("Noviembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros.
        /// </summary>
        internal static string Nuestros {
            get {
                return ResourceManager.GetString("Nuestros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        internal static string Octubre {
            get {
                return ResourceManager.GetString("Octubre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Pais {
            get {
                return ResourceManager.GetString("Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladar.
        /// </summary>
        internal static string Paladar {
            get {
                return ResourceManager.GetString("Paladar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persona.
        /// </summary>
        internal static string Persona {
            get {
                return ResourceManager.GetString("Persona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personas.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le ofrecemos un servicio de calidad donde su satisfacción es nuestra prioridad. Un espacio para degustar deliciosas bebidas y saborear una diversidad de ricas comidas criollas, aseguramos un Turismo saludable en Trinidad, uno de sus destinos favoritos para vacacionar en Cuba..
        /// </summary>
        internal static string Primera_parte {
            get {
                return ResourceManager.GetString("Primera_parte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajamos para usted, nuestro estimado cliente, con el fin de brindarle un servicio de calidad y satisfacción. Ofrecemos además el servicio de.
        /// </summary>
        internal static string Publicidad_hostal1 {
            get {
                return ResourceManager.GetString("Publicidad_hostal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donde le aseguramos una estancia con todas las atenciones que usted merece, dormitorios confortables y seguros, desayunos, almuerzos y comidas tradicionales cubanas para su deleite. No pierda tiempo, visítenos!!!.
        /// </summary>
        internal static string Publicidad_hostal2 {
            get {
                return ResourceManager.GetString("Publicidad_hostal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Acompañantes es obligatorio..
        /// </summary>
        internal static string Required_acompannantes {
            get {
                return ResourceManager.GetString("Required_acompannantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Comentario es obligatorio..
        /// </summary>
        internal static string Required_comentario {
            get {
                return ResourceManager.GetString("Required_comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Correo electrónico es obligatorio..
        /// </summary>
        internal static string Required_email {
            get {
                return ResourceManager.GetString("Required_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Fecha es obligatorio..
        /// </summary>
        internal static string Required_fecha {
            get {
                return ResourceManager.GetString("Required_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Fecha entrada es obligatorio..
        /// </summary>
        internal static string Required_fecha_entrada {
            get {
                return ResourceManager.GetString("Required_fecha_entrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Fecha salida es obligatorio..
        /// </summary>
        internal static string Required_fecha_salida {
            get {
                return ResourceManager.GetString("Required_fecha_salida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene que seleccionar al menos una habitación..
        /// </summary>
        internal static string Required_habitaciones {
            get {
                return ResourceManager.GetString("Required_habitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Hora es obligatorio..
        /// </summary>
        internal static string Required_hora {
            get {
                return ResourceManager.GetString("Required_hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Mensaje es obligatorio..
        /// </summary>
        internal static string Required_mensaje_contactenos {
            get {
                return ResourceManager.GetString("Required_mensaje_contactenos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Nombre y Apellidos es obligatorio..
        /// </summary>
        internal static string Required_nombre_apellidos {
            get {
                return ResourceManager.GetString("Required_nombre_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo País es obligatorio..
        /// </summary>
        internal static string Required_pais {
            get {
                return ResourceManager.GetString("Required_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo Contraseña es obligatorio..
        /// </summary>
        internal static string Required_password {
            get {
                return ResourceManager.GetString("Required_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservación.
        /// </summary>
        internal static string Reservacion {
            get {
                return ResourceManager.GetString("Reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La reservacion se eliminó correctamente..
        /// </summary>
        internal static string Reservacion_elimino {
            get {
                return ResourceManager.GetString("Reservacion_elimino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        internal static string Reservar {
            get {
                return ResourceManager.GetString("Reservar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Ahora.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        internal static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saludos.
        /// </summary>
        internal static string Saludos {
            get {
                return ResourceManager.GetString("Saludos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nos satisface poder recibirlo en nuestra casa desde el.
        /// </summary>
        internal static string Satisface_recibirlo {
            get {
                return ResourceManager.GetString("Satisface_recibirlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cocina es un arte que desarrollamos con delicadeza para lograr la satisfacción total del más exigente de los comensales, su deleite es nuestra primacía..
        /// </summary>
        internal static string Segunda_parte {
            get {
                return ResourceManager.GetString("Segunda_parte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        internal static string Septiembre {
            get {
                return ResourceManager.GetString("Septiembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        internal static string Servicios {
            get {
                return ResourceManager.GetString("Servicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Servicios.
        /// </summary>
        internal static string Servicios_hostal {
            get {
                return ResourceManager.GetString("Servicios_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio de gastronomía: desayuno, almuerzo, comida..
        /// </summary>
        internal static string Servicio_gastronomia {
            get {
                return ResourceManager.GetString("Servicio_gastronomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Reservación.
        /// </summary>
        internal static string Solicitud_reservacion {
            get {
                return ResourceManager.GetString("Solicitud_reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir imágenes.
        /// </summary>
        internal static string Subir_imagenes {
            get {
                return ResourceManager.GetString("Subir_imagenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamaño máximo permitido.
        /// </summary>
        internal static string Tamanno_maximo {
            get {
                return ResourceManager.GetString("Tamanno_maximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emelina - Paladar &amp; Hostal.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladar.
        /// </summary>
        internal static string Titulo_publicidad1 {
            get {
                return ResourceManager.GetString("Titulo_publicidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejores chefs.
        /// </summary>
        internal static string Titulo_publicidad2 {
            get {
                return ResourceManager.GetString("Titulo_publicidad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelencia y buen gusto.
        /// </summary>
        internal static string Titulo_publicidad2_hostal {
            get {
                return ResourceManager.GetString("Titulo_publicidad2_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú extenso.
        /// </summary>
        internal static string Titulo_publicidad3 {
            get {
                return ResourceManager.GetString("Titulo_publicidad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfacción y bienestar.
        /// </summary>
        internal static string Titulo_publicidad3_hostal {
            get {
                return ResourceManager.GetString("Titulo_publicidad3_hostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver todo el Menú.
        /// </summary>
        internal static string Todo_menu {
            get {
                return ResourceManager.GetString("Todo_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Galería.
        /// </summary>
        internal static string Ver_galeria {
            get {
                return ResourceManager.GetString("Ver_galeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        internal static string Viernes {
            get {
                return ResourceManager.GetString("Viernes", resourceCulture);
            }
        }
    }
}
